name: macos-x86_64

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.livemd'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.livemd'
      - '.github/FUNDING.yml'
      - '.github/workflows/nerves-*'
      - '.github/workflows/linux-*'
      - '.github/workflows/test-*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mix_test:
    runs-on: macos-13
    env:
      TFLITE_BEAM_CORAL_SUPPORT: "true"
      TFLITE_BEAM_PREFER_PRECOMPILED: "true"
      OTP_VERSION: "26.2.1"
      ELIXIR_VERSION: "1.16.0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OTP and Elixir
        run: |
          curl -fsSO https://elixir-lang.org/install.sh
          sh install.sh "elixir@${ELIXIR_VERSION}" "otp@${OTP_VERSION}"

      - name: Compile and Test
        run: |
          export OTP_MAIN_VER="${OTP_VERSION%%.*}"
          export PATH=$HOME/.elixir-install/installs/otp/${OTP_VERSION}/bin:$PATH
          export PATH=$HOME/.elixir-install/installs/elixir/${ELIXIR_VERSION}-otp-${OTP_MAIN_VER}/bin:$PATH

          mix local.hex --force
          mix local.rebar --force

          mix deps.get
          mix test
